### ISSUE TITLE
Remove Strictly Deprecated Classes

### ISSUE THREAD

**Issue by ruthtillman** [Art-and-Rare-Materials-BF-Ext/arm#2]
This is a set of Classes which the spreadsheet indicates should just be deprecated. Using the https://docs.google.com/spreadsheets/d/1G9gcsVrOWJz8ZFMMgHpHddy6M0jsD29aRFg2ZfXmKDk/edit spreadsheet, record progress in the "Status" column of the spreadsheet. See https://github.com/Art-and-Rare-Materials-BF-Ext/arm/issues/3 for more complex deprecations including properties.

Classes:

- [ ] arm:Accessioner
- [ ] arm:Accessioning
- [ ] arm:Acquisition
- [x] arm:Arrangement
- [ ] arm:Auction
- [ ] arm:Bequest
- [ ] arm:Borrower
- [ ] arm:Buyer
- [ ] arm:Claim of ownership
- [ ] arm:Claimant
- [ ] arm:CustodialEvent
- [ ] arm:CustodialHistory and related classes (as described in spreadsheet)
- [ ] arm:Deaccessioner
- [ ] arm:Deaccessioning
- [ ] arm:Dealer
- [ ] arm:Deposit
- [ ] arm:Depositor
- [ ] arm:Destroyer
- [ ] arm:Destruction
- [ ] arm:Discarder
- [ ] arm:Discarding
- [ ] arm:Disputant
- [ ] arm:Donation
- [ ] arm:Donor
- [ ] arm:Inheritance
- [ ] arm:Inheritor
- [ ] arm:Lender
- [ ] arm:Loan
- [ ] arm:Loss
- [ ] arm:Loss
- [x] arm:OclcNumber
- [ ] arm:Offer
- [ ] arm:Offer
- [ ] arm:Owner
- [ ] arm:Ownership
- [ ] arm:Recipient
- [ ] arm:Recoverer
- [ ] arm:Recovery
- [ ] arm:Repatriation
- [ ] arm:Repatriator
- [ ] arm:Sale
- [ ] arm:Seller
- [ ] arm:Testator
- [ ] arm:Theft
- [ ] arm:Thief
- [ ] arm:Transfer
- [ ] arm:Transferer
- [ ] arm:Witness
- [x] arm:SlipCase
- [x] arm:DustJacket
- [x] arm:WrapAroundBand
- [x] arm:Wrapper

**Comment by regineheberlein** [comment]
remove from merged file: 
* arm:Arrangement
* arm:OclcNumber
* arm:SlipCase
* arm:DustJacket

**Comment by regineheberlein** [comment]
remove from custodial history:
- [ ] arm:Accessioner (label "accessioner" on "AccessionerActivity" class?)
- [x] arm:Accessioning
- [ ] arm:Acquisition (label "acquisition" on "AcquisitionActivity" class?)
- [x] arm:Auction
- [x] arm:Bequest
- [ ] arm:Borrower (label "borrower" on "BorrowerActivity" class)
- [ ] arm:Buyer (label "buyer" on "BuyerActivity" class)
- [x] arm:Claim of ownership
- [ ] arm:Claimant (label "claimant" on "ClaimantActivity" class)
- [ ] arm:CustodialEvent (and subclasses)
  - [ ] https://w3id.org/arm/custodial_history/ontology/0.1/Deaccessioning
  - [ ] https://w3id.org/arm/custodial_history/ontology/0.1/Deposit
  - [ ] https://w3id.org/arm/custodial_history/ontology/0.1/Destruction
  - [ ] https://w3id.org/arm/custodial_history/ontology/0.1/Discarding
  - [ ] https://w3id.org/arm/custodial_history/ontology/0.1/Donation
  - [ ] https://w3id.org/arm/custodial_history/ontology/0.1/Inheritance
  - [ ] https://w3id.org/arm/custodial_history/ontology/0.1/Loan
  - [ ] https://w3id.org/arm/custodial_history/ontology/0.1/Loss
  - [ ] https://w3id.org/arm/custodial_history/ontology/0.1/Offer
  - [ ] https://w3id.org/arm/custodial_history/ontology/0.1/Ownership
  - [ ] https://w3id.org/arm/custodial_history/ontology/0.1/Recovery
  - [ ] https://w3id.org/arm/custodial_history/ontology/0.1/Repatriation
  - [ ] https://w3id.org/arm/custodial_history/ontology/0.1/Sale
  - [ ] https://w3id.org/arm/custodial_history/ontology/0.1/Theft
  - [ ] https://w3id.org/arm/custodial_history/ontology/0.1/Transfer
- [ ] arm:CustodialHistory and related classes (as described in spreadsheet)
- [ ] arm:Deaccessioner
- [ ] arm:Deaccessioning
- [ ] arm:Dealer
- [ ] arm:Deposit
- [ ] arm:Depositor
- [ ] arm:Destroyer
- [ ] arm:Destruction
- [ ] arm:Discarder
- [ ] arm:Discarding
- [ ] arm:Disputant
- [ ] arm:Donation
- [ ] arm:Donor
- [ ] arm:Inheritance
- [ ] arm:Inheritor
- [ ] arm:Lender
- [ ] arm:Loan
- [ ] arm:Loss
- [ ] arm:Loss
- [ ] arm:Offer
- [ ] arm:Offer
- [ ] arm:Owner
- [ ] arm:Ownership
- [ ] arm:Recipient
- [ ] arm:Recoverer
- [ ] arm:Recovery
- [ ] arm:Repatriation
- [ ] arm:Repatriator
- [ ] arm:Sale
- [ ] arm:Seller
- [ ] arm:Testator
- [ ] arm:Theft
- [ ] arm:Thief
- [ ] arm:Transfer
- [ ] arm:Transferer
- [ ] arm:Witness
- [ ] arm:WrapAroundBand
- [ ] arm:Wrapper

**Comment by regineheberlein** [comment]
deprecate custodialhistory--since it's in a separate file, do we need the above checklist? removing the above leaves behind only the object properties accessions/accessionedBy/hasCustodialHistory/isCustodialHistoryOf

- [x] arm:Accessioner 
- [x] arm:Accessioning
- [x] arm:Acquisition
- [x] arm:Auction
- [x] arm:Bequest
- [x] arm:Borrower 
- [x] arm:Buyer
- [x] arm:Claim of ownership
- [x] arm:Claimant 
- [x] arm:CustodialEvent (and subclasses)
  - [x] https://w3id.org/arm/custodial_history/ontology/0.1/Deaccessioning
  - [x] https://w3id.org/arm/custodial_history/ontology/0.1/Deposit
  - [x] https://w3id.org/arm/custodial_history/ontology/0.1/Destruction
  - [x] https://w3id.org/arm/custodial_history/ontology/0.1/Discarding
  - [x] https://w3id.org/arm/custodial_history/ontology/0.1/Donation
  - [x] https://w3id.org/arm/custodial_history/ontology/0.1/Inheritance
  - [x] https://w3id.org/arm/custodial_history/ontology/0.1/Loan
  - [x] https://w3id.org/arm/custodial_history/ontology/0.1/Loss
  - [x] https://w3id.org/arm/custodial_history/ontology/0.1/Offer
  - [x] https://w3id.org/arm/custodial_history/ontology/0.1/Ownership
  - [x] https://w3id.org/arm/custodial_history/ontology/0.1/Recovery
  - [x] https://w3id.org/arm/custodial_history/ontology/0.1/Repatriation
  - [x] https://w3id.org/arm/custodial_history/ontology/0.1/Sale
  - [x] https://w3id.org/arm/custodial_history/ontology/0.1/Theft
  - [x] https://w3id.org/arm/custodial_history/ontology/0.1/Transfer
- [x] arm:Deaccessioner
- [x] arm:Dealer
- [x] arm:Depositor
- [x] arm:Destroyer
- [x] arm:Discarder
- [x] arm:Disputant
- [x] arm:Donor
- [x] arm:Inheritor
- [x] arm:Lender
- [x] arm:Loss
- [x] arm:Owner
- [x] arm: Offer
- [x] arm:Recipient
- [x] arm:Recoverer
- [x] arm:Repatriator
- [x] arm:Seller
- [x] arm:Testator
- [x] arm:Thief
- [x] arm:Transferer
- [x] arm:Witness
